# Even Fibonacci numbers
# Problem 2 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibs(stopWhen = 2)
  if stopWhen <= 1
    stopWhen = 1
  end

  nums = [1,1]
  i = 1

  while nums.last < stopWhen
    nums.push(nums[i-1] + nums[i])
    i += 1
  end
  nums[0...-1]
end

nums = fibs(4000000)
sum = nums.inject(0) { |acc, n| n % 2 == 0 ? acc + n : acc } 
puts sum
